image: registry.gitlab.com/motorica-org/gitlab-ci-android:master

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/android/.gradle
- chmod +x ./android/gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - ./android/gradle/

build:
  stage: build
  script:
  - ./android/gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/