image: soluto/android-nodejs

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/android/.gradle
- chmod +x ./android/gradlew
- npm install -g code-push-cli
- npm install
- code-push login --accessKey d1c7ebcdcedcd1e62937069b703b485885a5afe6

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - ./android/gradle/
  - ./node_modules/

build:
  stage: build
  script:
  - cd android
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - android/app/build/outputs/