image: registry.gitlab.com/peterreisz/gitlab-ci-runner-java-node-android:master

stages:
- build

before_script:
- export GRADLE_USER_HOME=$(pwd)/android/.gradle
- chmod +x ./android/gradlew
- npm install

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - ./android/gradle/

build:
  stage: build
  script:
  - cd android
  - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/